#!/bin/bash -l
#PBS -N Fgen_ACCESS_Calculation_new
#PBS -A UWAS0157
#PBS -l walltime=00:10:00
#PBS -q casper@casper-pbs
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M xingcx2@uw.edu
#PBS -l select=2:ncpus=32:mpiprocs=1:mem=128GB

module load conda/latest
conda activate amoc-env

papermill /glade/u/home/stevenxu/AMOCproject/scripts/Fgen_calculation.ipynb /glade/u/home/stevenxu/AMOCproject/scripts/Fgen_calculation_result.ipynb

