#!/bin/bash -l
#PBS -N Fgen_ACCESS_Calculation
#PBS -A UWAS0157
#PBS -l walltime=00:10:00
#PBS -q casper@casper-pbs
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M xingcx2@uw.edu
#PBS -l select=1:ncpus=8:mpiprocs=1:mem=32GB

module load conda/latest
conda activate amoc-env

python Fgen_script.py 
