#!/bin/bash -l
#PBS -N Fgen_Calculation
#PBS -A UWAS0157
#PBS -l walltime=06:00:00
#PBS -q develop@desched1
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M xingcx2@uw.edu
#PBS -l select=4:ncpus=64:mem=64GB

module load conda/latest
conda activate amoc-env

python /glade/u/home/stevenxu/AMOCproject/scripts/FgenCalculation/dataDownload.py
