#!/bin/bash -l
#PBS -N Fgen_MMM
#PBS -A UWAS0157
#PBS -q develop@desched1
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=32:mem=128GB
#PBS -l place=shared
#PBS -j oe
#PBS -k eod

set -eo pipefail

# Run from the directory where the job was submitted.
cd "$PBS_O_WORKDIR"

echo "=== JOB INFO ==="
echo "HOST: $(hostname)"
echo "NODES:"
uniq "$PBS_NODEFILE"
echo "Total slots (nodefile lines): $(wc -l < "$PBS_NODEFILE")"
echo "WORKDIR: $PBS_O_WORKDIR"
date

module load conda/latest
conda activate amoc-env

# Avoid oversubscription by threaded numerical libraries.
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

python /glade/u/home/stevenxu/AMOCproject/scripts/FgenCalculation/Fgen_mean_calculation.py \
  --output-dir /glade/work/stevenxu/AMOC_models/MMM_binned_1deg_no_SAM0 \
  --models \
    ACCESS-CM2 \
    ACCESS-ESM1-5 \
    CAS-ESM2-0 \
    CanESM5 \
    CanESM5-1 \
    E3SM-1-0 \
    GISS-E2-1-G-CC \
    GISS-E2-2-G \
    ICON-ESM-LR \
    MIROC6 \
    MPI-ESM-1-2-HAM \
    MPI-ESM1-2-HR \
    MPI-ESM1-2-LR \
    MRI-ESM2-0 \
    NorESM2-LM \
    NorESM2-MM \
  --resume \
  --time-chunk 12
